services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    pull_policy: always
    ports:
      - "7687:7687"  # Bolt protocol port
      - "7444:7444"  # HTTP API port
    command:
      - "--log-level=INFO"  # Reduced verbosity for better performance
      - "--memory-limit=16384"  # Set memory limit to 16 GB
      - "--storage-mode=IN_MEMORY_ANALYTICAL"  # Enable Analytical Storage Mode
    volumes:
      - /Users/jluker/aonprd-parse/output_data/import_files:/var/lib/memgraph/import  # Mount import files directory

  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    pull_policy: always
    ports:
      - "3000:3000"  # Memgraph Lab web interface
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687



