# config/config.yaml
paths:
  input_folder: "input_data/raw_html_data"
  cleaned_html_data: "output_data/consolidated/unique_raw_html_data"
  manual_cleaned_html_data: "output_data/manual_cleaned_html_data"
  consolidated_dir: "output_data/consolidated"
  log_dir: "logs"
  decomposed_output_dir: "output_data/decomposed"
  condensed_output_dir: "output_data/condensed"
  processing_output_dir: "output_data/processed"
  processed_output_dir: "output_data/processed"
  import_files_dir: "output_data/import_files"

processing:
  max_files: 35000
  similarity_threshold: 0.99
  max_workers: 16

files:
  data_pickle: "data.pickle"
  structure_pickle: "structure.pickle"
  filtered_data_pickle: "filtered_data.pickle"
  filtered_structure_pickle: "filtered_structure.pickle"
  data_yaml: "data.yaml"
  structure_yaml: "structure.yaml"
  filtered_data_yaml: "filtered_data.yaml"
  filtered_structure_yaml: "filtered_structure.yaml"

database:
  consolidated_html_db: "output_data/consolidated/consolidated_html_data.db"
  crawler_db: "input_data/crawler_state.db"

memgraph:
  host: "localhost"
  port: 7687
  batch_size: 1000
